name: Dump and debug

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  # All jobs see this variable
  TEST_VAR: "Global"
  
## Gleaned from
#  https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    env:
      TEST_VAR: "Job"
    steps:
      - name: Output TEST_VAR job context
        run: echo '$TEST_VAR'
      - name: Output TEST_VAR step context
        env:
          TEST_VAR: "Step"
        run: echo '$TEST_VAR'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo '$GITHUB_CONTEXT'
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo '$JOB_CONTEXT'
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo '$STEPS_CONTEXT'
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo '$RUNNER_CONTEXT'
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo '$STRATEGY_CONTEXT'
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo '$MATRIX_CONTEXT'
  ## Gleaned from LinkedIn learning
  single_var_debug:
    runs-on: ubuntu-latest
    steps:
      - name: Actor
        run: echo "Actor: ${{ github.actor }}"
      - name: Output TEST_VAR global context
        run: echo '$TEST_VAR'
